oss:
  provider: minio
  endpoint: minioapi.szadmin.cn
  accessKey: EBPVrHftB014oEKdR9y8
  secretKey: PEIjn42TWp1jZ9SEl05ouhWG8nA8zv1zk3deD92G
  bucketName: test
  domain: https://minioapi.szadmin.cn
  is-https: true
  naming: original
